### ISSUE TITLE
osgearth的编译过程中出错，具体错误是osgearthqt 报错

### ISSUE THREAD

**Issue by wlhm1984** [haozzzzzzzz/osgEarthX#1]
osgearth的编译过程中出错，具体错误是osgearthqt 报错，难道是我的qt版本不一致吗，我用的最新的qt5.5.1，32位，vs2010的版本。

**Comment by haozzzzzzzz** [comment]
osgEarthX中的osgEarth没有还使用到qt库，如果你要加入qt库，需要自己配置一下cmake的路径。你可以使用cmake-gui，在生成目录选择框中打开environment/build/osgearth-2.6-build-2010文件夹，cmake-gui就会将所有的编译配置项列出。

**Comment by wlhm1984** [comment]
我使用cmake-gui配置的qt ，但是比较奇怪很多qt相关的项目生成出来没有头文件，需要手动引入，其他已经解决，但是Tool osgearth_package_qt 比较奇怪，里面有没有后缀的头文件，不知道怎么引入，您处理过类似的情况吗
![image](https://cloud.githubusercontent.com/assets/11953198/12546194/1c8d8bd8-c383-11e5-8b4a-94f6753f2e72.png)

**Comment by wlhm1984** [comment]
已经编译好了，非常感谢，另外如果我想升级osg 和osgearth到最新版本，应该改动哪些地方呢，有没有参照说明

**Comment by haozzzzzzzz** [comment]
本来打算要升级osg和osgearth的版本的，但是由于近期时间比较忙所有没有做。升级osg版本其实很简单，但是升级osgearth版本需要改动很多osgearth的源码，我之前尝试过升级osgearth版本到2.7.0，然后发现在AMD的显卡下有很多问题，所以暂时搁置了。

**Comment by wlhm1984** [comment]
非常感谢，您那里有没有api文档，我尝试做功能开发，找不到用那些方法，比如加载图层文件，加载模型文件等
